package com.unbank.mybatis.dao;

import com.unbank.mybatis.entity.ArticleInfo;
import com.unbank.mybatis.entity.ArticleInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int countByExample(ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int deleteByExample(ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer crawlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int insert(ArticleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int insertSelective(ArticleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    List<ArticleInfo> selectByExample(ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    ArticleInfo selectByPrimaryKey(Integer crawlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") ArticleInfo record, @Param("example") ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int updateByExample(@Param("record") ArticleInfo record, @Param("example") ArticleInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(ArticleInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_crawl
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int updateByPrimaryKey(ArticleInfo record);
}