package com.unbank.mybatis.dao;

import com.unbank.mybatis.entity.EveryDayNum;
import com.unbank.mybatis.entity.EveryDayNumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EveryDayNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int countByExample(EveryDayNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int deleteByExample(EveryDayNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer numId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int insert(EveryDayNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int insertSelective(EveryDayNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    List<EveryDayNum> selectByExample(EveryDayNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    EveryDayNum selectByPrimaryKey(Integer numId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") EveryDayNum record, @Param("example") EveryDayNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int updateByExample(@Param("record") EveryDayNum record, @Param("example") EveryDayNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(EveryDayNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_day_num
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int updateByPrimaryKey(EveryDayNum record);
}