package com.unbank.mybatis.dao;

import com.unbank.mybatis.entity.WebsiteParser;
import com.unbank.mybatis.entity.WebsiteParserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebsiteParserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int countByExample(WebsiteParserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int deleteByExample(WebsiteParserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int deleteByPrimaryKey(Integer parserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int insert(WebsiteParser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int insertSelective(WebsiteParser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    List<WebsiteParser> selectByExample(WebsiteParserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    WebsiteParser selectByPrimaryKey(Integer parserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int updateByExampleSelective(@Param("record") WebsiteParser record, @Param("example") WebsiteParserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int updateByExample(@Param("record") WebsiteParser record, @Param("example") WebsiteParserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int updateByPrimaryKeySelective(WebsiteParser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ptf_website_parser
     *
     * @mbggenerated Mon Sep 14 16:07:34 GMT+08:00 2015
     */
    int updateByPrimaryKey(WebsiteParser record);
}