package com.unbank.mybatis.entity;

import java.util.Date;

public class EveryWebDayNum {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_day_num_web.num_id
	 * @mbggenerated  Mon Sep 14 16:07:34 GMT+08:00 2015
	 */
	private Integer numId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_day_num_web.website_id
	 * @mbggenerated  Mon Sep 14 16:07:34 GMT+08:00 2015
	 */
	private Integer websiteId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_day_num_web.crawl_time
	 * @mbggenerated  Mon Sep 14 16:07:34 GMT+08:00 2015
	 */
	private Date crawlTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ptf_day_num_web.num
	 * @mbggenerated  Mon Sep 14 16:07:34 GMT+08:00 2015
	 */
	private Integer num;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_day_num_web.num_id
	 * @return  the value of ptf_day_num_web.num_id
	 * @mbggenerated  Mon Sep 14 16:07:34 GMT+08:00 2015
	 */
	public Integer getNumId() {
		return numId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_day_num_web.num_id
	 * @param numId  the value for ptf_day_num_web.num_id
	 * @mbggenerated  Mon Sep 14 16:07:34 GMT+08:00 2015
	 */
	public void setNumId(Integer numId) {
		this.numId = numId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_day_num_web.website_id
	 * @return  the value of ptf_day_num_web.website_id
	 * @mbggenerated  Mon Sep 14 16:07:34 GMT+08:00 2015
	 */
	public Integer getWebsiteId() {
		return websiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_day_num_web.website_id
	 * @param websiteId  the value for ptf_day_num_web.website_id
	 * @mbggenerated  Mon Sep 14 16:07:34 GMT+08:00 2015
	 */
	public void setWebsiteId(Integer websiteId) {
		this.websiteId = websiteId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_day_num_web.crawl_time
	 * @return  the value of ptf_day_num_web.crawl_time
	 * @mbggenerated  Mon Sep 14 16:07:34 GMT+08:00 2015
	 */
	public Date getCrawlTime() {
		return crawlTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_day_num_web.crawl_time
	 * @param crawlTime  the value for ptf_day_num_web.crawl_time
	 * @mbggenerated  Mon Sep 14 16:07:34 GMT+08:00 2015
	 */
	public void setCrawlTime(Date crawlTime) {
		this.crawlTime = crawlTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ptf_day_num_web.num
	 * @return  the value of ptf_day_num_web.num
	 * @mbggenerated  Mon Sep 14 16:07:34 GMT+08:00 2015
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ptf_day_num_web.num
	 * @param num  the value for ptf_day_num_web.num
	 * @mbggenerated  Mon Sep 14 16:07:34 GMT+08:00 2015
	 */
	public void setNum(Integer num) {
		this.num = num;
	}
}